### ISSUE TITLE
Mac OS 10.10 cant start it

### ISSUE THREAD

**Issue by aneitzel** [madengr/ham2mon#1]
Hi,

after clone GIT to my MAC and fire up "./ham2mon.py -a "uhd" -n 8 -f 146E6 -r 4E6 -g 30 -s -60 -v 0 -t 10 -w" i got this error:

mac:apps Andre$ ./ham2mon.py -a "hackrf" -n 8 -f 146E6 -r 4E6 -g 30 -s -60 -v 0 -t 10 -w
Mac OS; Clang version 6.1.0 (clang-602.0.53); Boost_105800; UHD_003.008.005-MacPorts-Release

Traceback (most recent call last):
  File "./ham2mon.py", line 126, in <module>
    curses.wrapper(main)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./ham2mon.py", line 51, in main
    lockout_file_name)
  File "/Users/Andre/ham2mon/apps/scanner.py", line 65, in **init**
    record)
  File "/Users/Andre/ham2mon/apps/receiver.py", line 258, in **init**
    fft_length)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gnuradio/blocks/blocks_swig1.py", line 426, in make
    return _blocks_swig1.stream_to_vector_make(itemsize, nitems_per_block)
RuntimeError: gr::io_signature(3)
mac:apps Andre$ 

Any Idea whats wrong?

thanks and regards André

**Comment by madengr** [comment]
It’s probably not finding the hackrf. Can you try the flow_example.grc, setting the osmocom source device arguments to hackrf?

Lou

**Comment by aneitzel** [comment]
Hi, you got it! Shame, my hackrf was not connected via usb.

Thanks for help, good tool!
regards from germany, André
