### ISSUE TITLE
RuntimeError: gr::io_signature(3)  - Any Idea?

### ISSUE THREAD

**Issue by ar8001** [madengr/ham2mon#10]
./ham2mon.py -a "rtl" -n 4 -f 145E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -wlinux; GNU C++ version 4.6.3; Boost_104900; UHD_003.004.002-0-unknown

Traceback (most recent call last):
  File "./ham2mon.py", line 131, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./ham2mon.py", line 55, in main
    freq_correction, record, lockout_file_name, play)
  File "/home/pi/ham2mon/apps/scanner.py", line 69, in **init**
    hw_args, freq_correction, record, play)
  File "/home/pi/ham2mon/apps/receiver.py", line 450, in **init**
    integrate_ff = blocks.integrate_ff(100, fft_length)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig3.py", line 287, in make
    return _blocks_swig3.integrate_ff_make(_args, *_kwargs)
TypeError: integrate_ff_make() takes at most 1 argument (2 given)
pi@raspberrypi ~/ham2mon/apps $

**Comment by madengr** [comment]
> TypeError: integrate_ff_make() takes at most 1 argument (2 given)

Yes, you are using an old version of GNU radio that does not accept vectors into the integrator.  You need to update.  Your UHD is also very old (not that you are using it, but that was released in July 2012).  I just tested with the development branches and it is working fine.

Same issue here:

https://github.com/madengr/ham2mon/issues/6

You need at least GNU Radio 3.7.8
