### ISSUE TITLE
RuntimeError: gr::io_signature(3)

### ISSUE THREAD

**Issue by JonTabor** [madengr/ham2mon#11]
Hey, I didn't find any answers for this, so I thought I'd ask.  I'm on openSUSE 42.1.  gnuradio is version 3.7.8-3.11.  I have a generic RTL2832U.  gqrx works, so I know the RTL is accessible via gnuradio.

Running this:
./ham2mon.py -a "rtl" -n 4 -f 145E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -w

And I get this:

Traceback (most recent call last):
  File "./ham2mon.py", line 136, in <module>
    curses.wrapper(main)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./ham2mon.py", line 58, in main
    priority_file_name, play)
  File "/home/taborj/ham2mon/apps/scanner.py", line 73, in **init**
    hw_args, freq_correction, record, play)
  File "/home/taborj/ham2mon/apps/receiver.py", line 435, in **init**
    fft_length)
  File "/usr/lib64/python2.7/site-packages/gnuradio/blocks/blocks_swig1.py", line 389, in make
    return _blocks_swig1.stream_to_vector_make(_args, *_kwargs)
RuntimeError: gr::io_signature(3)

Any thoughts?

**Comment by madengr** [comment]
Sorry, just saw this issue.  You need to remove the kernel module like so:

sudo rmmod dvb_usb_rtl28xxu

If you google "rtl sdr blacklist" you'll see several examples of making this permanent.

**Comment by sa5bke** [comment]
I also got something similar when I start ham2mon.py without any arguments. 

linux; GNU C++ version 5.3.1 20160413; Boost_105800; UHD_003.009.004-release

```
Traceback (most recent call last):
  File "./ham2mon.py", line 137, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./ham2mon.py", line 59, in main
    priority_file_name, play, audio_bps)
  File "/home/esn/src/ham2mon/apps/scanner.py", line 77, in __init__
    audio_bps)
  File "/home/esn/src/ham2mon/apps/receiver.py", line 442, in __init__
    fft_length)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig1.py", line 431, in make
    return _blocks_swig1.stream_to_vector_make(itemsize, nitems_per_block)
RuntimeError: gr::io_signature(3)

Isn´t the intended behavior to print the possible arguments / help? 

I use a HackRF and after figuring out what arguments I should use everything works fine. I might come up with some code changes to fix this with the help screen.

**Comment by pavel-i-am** [comment]
@madengr , I have the same problem with Ettus b205 board. Any idea how this can be resolved? Thanks.

➜  apps git:(master) python ham2mon.py -w
Mac OS; Clang version 7.3.0 (clang-703.0.31); Boost_106000; UHD_003.009.004-0-unknown

```
Traceback (most recent call last):
  File "ham2mon.py", line 137, in <module>
    curses.wrapper(main)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "ham2mon.py", line 59, in main
    priority_file_name, play, audio_bps)
  File "/Users/phoenix/ham2mon/apps/scanner.py", line 77, in __init__
    audio_bps)
  File "/Users/phoenix/ham2mon/apps/receiver.py", line 442, in __init__
    fft_length)
  File "/usr/local/lib/python2.7/site-packages/gnuradio/blocks/blocks_swig1.py", line 231, in make
    return _blocks_swig1.stream_to_vector_make(itemsize, nitems_per_block)
RuntimeError: gr::io_signature(3)
```

**Comment by madengr** [comment]
Does uhd_find_devices work?

**Comment by pavel-i-am** [comment]
@madengr , the drivers work just fine with gqrx, osmocom_fft and gnuradio. If there's any more useful information I can provide, please let me know.

```
uhd_find_devices
Mac OS; Clang version 7.3.0 (clang-703.0.31); Boost_106000; UHD_003.009.004-0-unknown

-- Loading firmware image: /usr/local/Cellar/uhd/003.009.004/share/uhd/images/usrp_b200_fw.hex...
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    type: b200
    name: B205i
    serial: (removed)
    product: B205mini

```

**Comment by pavel-i-am** [comment]
@madengr , sorry for the panic my friend, it seems to be working now. Probably I messed up some system components in the past, and changed it since then. Have a nice day and thanks for stopping by!
