### ISSUE TITLE
Help running under Debian/Rasbian

### ISSUE THREAD

**Issue by rcampbell75** [madengr/ham2mon#17]
Get the following dump when trying to run the program:

linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

Traceback (most recent call last):
  File "./ham2mon.py", line 137, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./ham2mon.py", line 59, in main
    priority_file_name, play, audio_bps)
  File "/opt/ham2mon/apps/scanner.py", line 77, in **init**
    audio_bps)
  File "/opt/ham2mon/apps/receiver.py", line 457, in **init**
    integrate_ff = blocks.integrate_ff(100, fft_length)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig3.py", line 592, in make
    return _blocks_swig3.integrate_ff_make(_args, *_kwargs)
TypeError: integrate_ff_make() takes at most 1 argument (2 given)

**Comment by rcampbell75** [comment]
Nevermind...

If anyone has any errors, guess you need GNURadio v3.7.8 or newer for this to work.  Wish distros would quit using older versions.
