### ISSUE TITLE
Curses error

### ISSUE THREAD

**Issue by starvald** [madengr/ham2mon#22]
Running on Antergos Linux i get this error on the latest from git, i do have an older version from mid 2016 which still seems to work ok.

```
[lee@Plasma apps]$ python2 ham2mon.py -a "airspy" -n 7 -f 156935000 -r 2500000  -g 12 -s -75 -t 10 -w -p priority-marine.txt -m
linux; GNU C++ version 7.1.1 20170516; Boost_106400; UHD_003.010.001.001-0-unknown

Traceback (most recent call last):
  File "ham2mon.py", line 147, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "ham2mon.py", line 96, in main
    rxwin.draw_rx()
  File "/run/media/storageEXT4/compiles/ham2mon/apps/cursesgui.py", line 379, in draw_rx
    self.win.addnstr(10, 1, text, 15)
_curses.error: addnstr() returned ERR
```

**Comment by madengr** [comment]
By older version, do you mean of ham2mon, or Linux?  Also make sure your xterm is big enough. If it is narrower than 80 columns it will bomb.

**Comment by starvald** [comment]
older version of ham2mon, tried making the xterm bigger still crashes out.

**Comment by starvald** [comment]
I did a bisect if that helps.
```

[lee@Plasma ham2mon]$ git pull
Already up-to-date.
[lee@Plasma ham2mon]$ git bisect start
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[lee@Plasma ham2mon]$ git bisect bad d15fd94b253a1a854a7f106dd105a3d83dcbee00
[lee@Plasma ham2mon]$ git bisect good 7305ebf07d5fb089ce97d1ebef0d71d8efd69594
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[7abad4e00f1392e1151359a6bf491b160bfabf6c] Corrected README formatting errors
[lee@Plasma ham2mon]$ git bisect bad
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[ef1492e2ad99e63ddc87cfeb54a13d119d81d47f] Merge pull request #3 from m0mik/hackrf_if_bb_gain
[lee@Plasma ham2mon]$ git bisect bad
Bisecting: 2 revisions left to test after this (roughly 1 step)
[ca54974f6a759be9ce4b75a0b276c53babcae803] Merge pull request #2 from madengr/master
[lee@Plasma ham2mon]$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 1 step)
[173b4ba2cfda4a74ad3ca2c385c888d606a6889c] corrected default values and removed whitespace
[lee@Plasma ham2mon]$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[9154120cbe0a2aba87dd00f8d465e8f120be5b3e] Added IF and BB gain for HackRF compatibility.
[lee@Plasma ham2mon]$ git bisect bad
9154120cbe0a2aba87dd00f8d465e8f120be5b3e is the first bad commit
commit 9154120cbe0a2aba87dd00f8d465e8f120be5b3e
Author: Mike Jameson <mikejamo@gmail.com>
Date:   Thu May 11 22:12:03 2017 +0100

    Added IF and BB gain for HackRF compatibility.

:100644 100644 355a3575cc8de1ce5a084c10028c2295c6ea9e95 d6a91eb717863ef5e5cf9c1e9ce64842e7402fc5 M   README.md
:040000 040000 da777356df0ae2bdc49bbbc1ddcdcb0eda9ae75b ce634fd3a4c29b6f5754668988da688ea6900fc6 M   apps
[lee@Plasma ham2mon]$ 

```

**Comment by m0mik** [comment]
Hi,

Does it work with minimal arguments on the command line?

Could you try:

./ham2mon.py -a "airspy" -n 1 -f 156935000

Thanks,

Mike

**Comment by m0mik** [comment]
I missed off the sample rate previously.

Try:
./ham2mon.py -a "airspy" -n 1 -f 156935000 -r 2500000

Thanks

**Comment by madengr** [comment]
Also try running just the cursesgui.py, as it will run with simulated spectrum data.

**Comment by starvald** [comment]
ok, i've got it working.
the console needs to be bigger than is used to need which caused my confusion.
the older version will work with smaller konsole.

thanks for everyones help.
