### ISSUE TITLE
It works on Rpi?

### ISSUE THREAD

**Issue by jeffersonpimenta** [madengr/ham2mon#23]
Hi folks,

I'm trying use this script on RP3, but i had received the message:

./ham2mon.py -a "rtl" -n 4 -f 145E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -w
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

Traceback (most recent call last):
  File "./ham2mon.py", line 147, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./ham2mon.py", line 59, in main
    priority_file_name, play, audio_bps)
  File "/home/pi/Desktop/ham2mon/ham2mon/apps/scanner.py", line 79, in __init__
    audio_bps)
  File "/home/pi/Desktop/ham2mon/ham2mon/apps/receiver.py", line 461, in __init__
    integrate_ff = blocks.integrate_ff(100, fft_length)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig3.py", line 592, in make
    return _blocks_swig3.integrate_ff_make(*args, **kwargs)
TypeError: integrate_ff_make() takes at most 1 argument (2 given)

Any ideas?

**Comment by madengr** [comment]
You probably have an old version of GNU Radio.  What version do you have?

**Comment by jeffersonpimenta** [comment]
3.7.5

**Comment by madengr** [comment]
You need 3.7.8 or later.  See here:

https://github.com/madengr/ham2mon/issues/10

**Comment by jeffersonpimenta** [comment]
No success yet: try to install GNC using pybombs but it freezes.
