### ISSUE TITLE
Why the error is coming?/

### ISSUE THREAD

**Issue by srshounak** [madengr/ham2mon#29]
IMSI-catcher# python scan-and-livemon
Locating potential GSM base station frequencies (this can take a few minutes).
Traceback (most recent call last):
  File "scan-and-livemon", line 102, in <module>
    main()
  File "scan-and-livemon", line 78, in main
    list = find_gsm_bases()
  File "scan-and-livemon", line 30, in find_gsm_bases
    scanner = imp.load_source('scanner', grgsm_scanner_path)
  File "/usr/bin/grgsm_scanner", line 36, in <module>
    import osmosdr
  File "/usr/lib/python2.7/dist-packages/osmosdr/__init__.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 17, in <module>
    _osmosdr_swig = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_osmosdr_swig')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _osmosdr_swig

**Comment by john-** [comment]
You probably meant to post that here: https://github.com/Oros42/IMSI-catcher
