### ISSUE TITLE
Won't run on Raspberry Pi 3

### ISSUE THREAD

**Issue by regulatre** [madengr/ham2mon#33]
When I invoke the application I see flashes of errors that clear away quickly before they can be read and I see text staircasing. In an attempt to calm the output I piped the output into strings so the VT terminal commands won't work. Below is a snippet of the errors I could catch. 
 

```
# pushd ~/git/ham2mon/apps/ && ./ham2mon.py -w -r 1500000 -d 0 -f 462562500 -a rtl 2>&1 | strings | tee /tmp/output.txt 
~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~
linux; GNU C++ version 6.2.0 20161010; Boost_106100; UHD_003.009.005-0-unknown
[?1049h
[1;24r
[?7h
[?1l
>Traceback (most recent call last):
  File "./ham2mon.py", line 147, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 49, in wrapper
    curses.nocbreak()
_curses.error: nocbreak() returned ERR
root@tonka:~/git/ham2mon/apps# pushd ~/git/ham2mon/apps/ && ./ham2mon.py -a "rtl" -n 4 -f 145E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -w
~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~/git/ham2mon/apps ~
linux; GNU C++ version 6.2.0 20161010; Boost_106100; UHD_003.009.005-0-unknown


RuntimeError: SDR hardware not detected or insufficient USB permissions. Try running as root.



# uname -a
Linux tonka 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

# dpkg --list |grep -i rtl
ii  librtlsdr0:armhf                       0.5.3-11+rpt1                        armhf        Software defined radio receiver for Realtek RTL2832U (library)
ii  rtl-sdr                                0.5.3-11+rpt1                        armhf        Software defined radio receiver for Realtek RTL2832U (tools)
ii  soapysdr0.5-2-module-rtlsdr:armhf      0.2.2-2                              armhf        RTL-SDR device support for SoapySDR

# dpkg --list |grep -i radio
ii  gnuradio                               3.7.10.1-2                           armhf        GNU Radio Software Radio Toolkit
ii  gnuradio-dev                           3.7.10.1-2                           armhf        GNU Software Defined Radio toolkit development
ii  gr-air-modes                           0.0.2.c29eb60-1                      armhf        Gnuradio Mode-S/ADS-B radio
ii  gr-fcdproplus                          3.7.25.4b6464b-2                     armhf        Funcube Dongle Pro Plus controller for GNU Radio
ii  gr-fosphor                             3.7.0.2.7b6b996-1                    armhf        gnuradio fosphor block (GPU spectrum display)
ii  gr-iqbal                               0.37.2-7                             armhf        GNU Radio Blind IQ imbalance estimator and correction

# lsusb
Bus 001 Device 004: ID 0bda:2832 Realtek Semiconductor Corp. RTL2832U DVB-T
Bus 001 Device 005: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 006: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by john-** [comment]
So you are using Soapy to interlace to the RTL dongle or Osmocom?  If Soapy then I would not expect things to work.  Assuming the ham2mon readme is accurate than it needs osmocom drivers.   For my Armbian install that means installing osmo-sdr and gr-osmosdr.

**Comment by ITCMD** [comment]
https://github.com/ta6o/ham2mon
