### ISSUE TITLE
error when try python ham2mon.py -a "rtl" Ubuntu 18.04

### ISSUE THREAD

**Issue by khanfar** [madengr/ham2mon#35]
please help i got this error when try to run python ham2mon.py
python ham2mon.py -a "rtl"
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

Traceback (most recent call last):
  File "ham2mon.py", line 147, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "ham2mon.py", line 96, in main
    rxwin.draw_rx()
  File "/home/mwk/Desktop/ham2mon-master/apps/cursesgui.py", line 380, in draw_rx
    self.win.addnstr(10, 1, text, 15)
_curses.error: addnstr() returned ERR

**Comment by madengr** [comment]
Try making your xterm bigger.

**Comment by khanfar** [comment]
how to make xterm bigger ?

**Comment by khanfar** [comment]
you mean terminal font size ?

**Comment by khanfar** [comment]
i got it thanks ,,, but how to add list of frequency i want to monitor in scan ??

**Comment by john-** [comment]
You do not specify a list of frequencies to scan.

You specify the center frequency and you will get a range of bandwidth centered on that.   The width will be based on bandwidth you specify (of course limited by your hardware).

**Comment by madengr** [comment]
See documentation.  There is a priority.txt you can add, though the basis of the program is that it finds whatever is in the bandwidth.  You only need a priority file if you have more channels than demodulators.

**Comment by khanfar** [comment]
i try this and the gui come up but no activity 
./ham2mon.py -a "rtl" -n 4 -f 446E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -w
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

rtlsdr_demod_write_reg failed with -7
rtlsdr_demod_read_reg failed with -7
r82xx_write: i2c wr failed=-7 reg=06 len=1

**Comment by john-** [comment]
Make sure your setup works with the rtl tools before working with ham2mon.    This will rule out usual problems like trying to use a USB hub with not enough power, basic access issues, etc.
